### ISSUE TITLE
User Story: Create Bag app

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#1]
**EPIC : Apps #2**

As a **developer** I can **create a Bag app** so that **I can add products to my Bag**

**Acceptance Criteria :**
- Create Bag app
- Have views, templates & urls setup for Bag page

**Tasks :**
- [x] Create bag app via terminal
- [x] App app to installed apps in settings.py
- [x] Link up urls
- [x] Create views
- [x] Create template for bag page
- [x] Create models for Bag
