### ISSUE TITLE
User Story: Search for a product by name or description

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#11]
**EPIC :  Sorting and Searching https://github.com/BreakellrZ/ParadisePending_e-commerce/issues/14**

As a **user** I can **Search for a product by name or description** so that **I can use the search bar to find what I am looking for easier.**

**Acceptance Criteria :**
- Have a search bar for users to use
- If user types in something in the search bar, if it matches something in our database it should bring up that product/products, if not it should tell the user we do not have that in our store

**Tasks :**
- [x] Create a search form in base.html
- [x] Allow users to search the site via the search bar
- [x] Use a get method within the form to get the information from the database and link it to url 'products'
- [x] Show users the products they searched for or provide an error message to them if what they searched for is not currently on our store,
