### ISSUE TITLE
User Story: Select the size and quantity of a product

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#12]
**EPIC : Purchasing and Checkouthttps://github.com/BreakellrZ/ParadisePending_e-commerce/issues/15**

As a **user** I can **Select the size and quantity of a product** so that **buy as many as I would like and buy them in my size**

**Acceptance Criteria :**
- Have the option to select what size you would like
- Be able to select more then one item per purchase

**Tasks :**
- [x] Creat a form that allows users to select the quantity of a product
- [x] Create a select form for users to select which size they would like
- [x] use Javascript to code the functionality
