### ISSUE TITLE
User Story: View Items in a bag

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#13]
**EPIC : Purchasing and Checkout https://github.com/BreakellrZ/ParadisePending_e-commerce/issues/15**

As a **user** I can **View items in a bag** so that **I can see exactly what I will be purchasing**

**Acceptance Criteria :**
- Have a bag where users can see what items they will be purchasing  
- Show price, quantity etc.

**Tasks :**
- [x] Create a bag app 
- [x] Create bag html template include all the neccessary functionality to show item, price, quantity etc inside of the bag
- [x] Create view to show bag contents page
