### ISSUE TITLE
User Story: Adjust quantity of  items in bag

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#14]
**EPIC : Purchasing and Checkout https://github.com/BreakellrZ/ParadisePending_e-commerce/issues/15**

As a **user** I can **adjust the quanity of items in a bag** so that **I can add or delete more items if I change my mind in the bag*

**Acceptance Criteria :**
- Be able to change the quantity of items in my bag
- Be able to add or delete items in bag

**Tasks :**
- [x] Create a quantity form 
- [x] Provide buttons to update and or remove items from bag
- [x] use Javascript to code the functionality
