### ISSUE TITLE
User Story: Enter Payment Information

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#15]
**EPIC : Purchasing and Checkout https://github.com/BreakellrZ/ParadisePending_e-commerce/issues/15**

As a **user** I can **enter payment information** so that **I can purchase items**

**Acceptance Criteria :**
- Be able to enter all payment information
- Have a payment form with the neccessary Fields such as name, address, and card details etc.
- Show Order sumary 
- Payment is proccesed via stripe

**Tasks :**
- [x] Create a payment form in checkout.html
- [x] Be able to save delivery information to profile
- [x] use Javascript to code the functionality
- [x] Setup Stripe
