### ISSUE TITLE
User Story: View order confirmation after checkout

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#16]
**EPIC : Purchasing and Checkout https://github.com/BreakellrZ/ParadisePending_e-commerce/issues/15**

As a **user** I can **aview order confirmation after checkout** so that **I can view what I have just purchased*

**Acceptance Criteria :**
- Takes user to a new page after payment to show them the payment was successful
- Show all order details after payment confirmation

**Tasks :**
- [x] Create a checkout_success template 
- [x] Create Order model
- [x] Show all order details to user
