### ISSUE TITLE
User Story: Create and View my own Profile as a user

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#19]
**EPIC : User Accounts, Authentication, Authorization & Registration https://github.com/BreakellrZ/ParadisePending_e-commerce/issues/4**

As a **user** I can **create and view my own profile** so that **I can save my account information and view my previous purchases etc**

**Acceptance Criteria :**
- Users can create a profile
- Users can view there previous purchases in their profile
- Users can update their delivery information

**Tasks :**
- [x] Create profile app
- [x] Create profile template that shows delivery information form and previous purchases
- [x] Make users have Crud functionality for delivery information.
