### ISSUE TITLE
User Story: Create checkout app

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#2]
**EPIC : Apps #2**

As a **developer** I can **create a Checkout app** so that **I can checkout my products**

**Acceptance Criteria :**
- Create Checkout app
- Have views, templates & urls setup for Checkout page so users can purchase items

**Tasks :**
- [x] Create checkout app via terminal
- [x] App app to installed apps in settings.py
- [x] Link up urls
- [x] Create views
- [x] Create template for checkout page
