### ISSUE TITLE
User Story: SEO implementation

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#23]
**EPIC : SEO & Marketing** #https://github.com/BreakellrZ/ParadisePending_e-commerce/issues/9

As a **developerr** I can **implement good SEO** so that **Paradise Pending has a better chance of getting viewd by users.*

**Acceptance Criteria :**
- Have a robots.txt file
- Have a sitemap.xml file
- Have meta tags in head of base html file

**Tasks :**
- [x] Create Meta tags in base.html
- [x] Create robots.txt file
- [x] Create sitemap.xml file
