### ISSUE TITLE
User Story: Create profiles app

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#3]
**EPIC : Apps #2**

As a **developer** I can **create a profiles app** so that **I can allow users to have a profile and to be able to view their products purchased etc**

**Acceptance Criteria :**
- Create profiles app
- Have views, templates & urls setup for profiles page

**Tasks :**
- [x] Create profile app via terminal
- [x] App app to installed apps in settings.py
- [x] Link up urls
- [x] Create views
- [x] Create template for profile page
