### ISSUE TITLE
User Story: Create Reviews app

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#4]
**EPIC : Apps #2**

As a **developer** I can **create a Review app** so that **users can write reviews**

**Acceptance Criteria :**
- Create a review app
- Have views, templates, models & urls setup for Review page

**Tasks :**
- [x] Create Reviews app via terminal
- [x] App app to installed apps in settings.py
- [x] Link up urls
- [x] Create a Review Model
- [x] Create views so users can write reviews
- [x] Create template for Reviews page
