### ISSUE TITLE
User Story: Deploy to Heroku

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#5]
EPIC : Initial Setup + Settings https://github.com/BreakellrZ/ParadisePending_e-commerce/issues/1

As a **developer** I can **deploy to Heroku** so that **my project can be hosted by Heroku and deployed.**

**Acceptance Criteria :**
- Deploy to Heroku without any errors
- Have a live fully functional working e-commerce store deployed on Heroku

**Tasks :**
- [x] Setup Heroku account
- [x] Setup Deployment - configure all neccessary settings such as config vars
- [x] Hit Deploy to Heroku
