### ISSUE TITLE
User Story: View a list of products

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#6]
**EPIC :  Viewing and Navigation https://github.com/BreakellrZ/ParadisePending_e-commerce/issues/13**

As a **user** I can **view a list of products** so that ** I can view them and add them to my bag to purchase.**

**Acceptance Criteria :**
- View all products
- Be able to individually click on each product to take me to product detail page

**Tasks :**
- [x] Create products.html template
- [x] Use a for loop to loop through and show all products to users
- [x] Be able to view products based on sorting then by price etc
