### ISSUE TITLE
User Story: View individual Product details

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#7]
**EPIC : Viewing and Navigation https://github.com/BreakellrZ/ParadisePending_e-commerce/issues/13**

As a **user** I can **view individual Product details** so that **I can read all of the details about that specific Product.**

**Acceptance Criteria :**
- View all products details individually
- Show all details about product 
- Be able to add product to checkout bag

**Tasks :**
- [x] Create products_details.html template
- [x] Show all information per individual product using template tags
- [x] Be able to add to checkout bag or go back to previous page via buttons
