### ISSUE TITLE
User Story:  View the total of the users purchases

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#8]
**EPIC : Viewing and Navigation https://github.com/BreakellrZ/ParadisePending_e-commerce/issues/13**

As a **user** I can **view the total of my purchases** so that **I know how much I need to pay.**

**Acceptance Criteria :**
- Shows the user how much is needed to pay
- Show all details about price per item

**Tasks :**
- [x] Create products_details.html template
- [x] Show all information per individual product using template tags
- [x] If user selects more then one of the same t-shirt it will show the combined price to the user
- [x] Use javascript to code this functionality in - be able to increment and decrement the quantity of each product and show the combined price
