### ISSUE TITLE
User Story: Sort the list of available products

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/e-commerce#9]
**EPIC : Sorting and Searching https://github.com/BreakellrZ/ParadisePending_e-commerce/issues/14**

As a **user** I can **sort the products** so that **I can view only certain products depending on what I am sorting for**

**Acceptance Criteria :**
- Only show products the correct way in which the user is sorting for
- Provide a number of ways for the user to sort the products

**Tasks :**
- [x] Create a select box for Users to choose in what way they would like to sort the products
- [x] Include price, category, etc.
- [x] use Javascript to code the sorting functionality
